if(NOT PYTHONINTERP_FOUND)
        find_package(PythonInterp REQUIRED)
endif()

FUNCTION(INSTALL_VIA_PIP module RESULT_NAME)
#check for pip. The pip installer needs the python-xml module.
execute_process(COMMAND ${PYTHON_EXECUTABLE} -m pip freeze OUTPUT_VARIABLE PYTHON_PACKAGE_LIST)
    if ("${PYTHON_PACKAGE_LIST}" STREQUAL "")
        execute_process(COMMAND pip freeze OUTPUT_VARIABLE PYTHON_PACKAGE_LIST)
        if ("${PYTHON_PACKAGE_LIST}" STREQUAL "")
            message(WARNING "Failed to find pip. Pip is required to automatically install ${module}. Will now install pip.")
            file(DOWNLOAD https://bootstrap.pypa.io/get-pip.py ./get-pip.py --user STATUS SUCCESS)
            LIST(GET ${SUCCESS} 0 PIPINSTALLED)
            if (NOT ${PIPINSTALLED})
                message(WARNING "CMake was not able to download pip. Trying with a direct call to curl")
                execute_process(COMMAND curl -k https://bootstrap.pypa.io/get-pip.py -o get-pip.py RESULT_VARIABLE result)
            endif()
            execute_process(COMMAND ${PYTHON_EXECUTABLE} ./get-pip.py --user RESULT_VARIABLE RES)
#            message(${RES})
            if(${RES})#FIXME: Check wether this works for other versions...
                message(WARNING "Not able to successfully execute Pip. assuming this is due to an old version of Python.")
                file(DOWNLOAD https://pypi.python.org/packages/25/57/0d42cf5307d79913a082c5c4397d46f3793bc35e1138a694136d6e31be99/pip-1.1.tar.gz ./pip-1.1.tar.gz STATUS SUCCESS)
                LIST(GET ${SUCCESS} 0 PIPINSTALLED)
                if (NOT ${PIPINSTALLED})
                    message("CMake was not able to download pip-1.1. Trying with a direct call to curl")
                    execute_process(COMMAND curl -k https://pypi.python.org/packages/25/57/0d42cf5307d79913a082c5c4397d46f3793bc35e1138a694136d6e31be99/pip-1.1.tar.gz -o ./pip-1.1.tar.gz RESULT_VARIABLE result)
                    execute_process(COMMAND tar -xzvf ./pip-1.1.tar.gz)
                    execute_process(COMMAND python ./pip-1.1/setup.py install)#pip needs setuptools. 
                endif()
            endif()
        endif()
    endif()
# pip is present

message(STATUS "Installing ${module}")
execute_process(COMMAND ${PYTHON_EXECUTABLE} -c "import sys; print('%s.%s' % sys.version_info[0:2])"
 OUTPUT_VARIABLE PYVER)

 if(${PYVER} VERSION_LESS "2.6" )
    MESSAGE(WARNING "Installing to user folders via pip is supported with python 2.6. Will try to install as root now. Expect this to fail and mess up your system.")
    else()
    SET(PIPMODE "--user")
 endif()
        execute_process(COMMAND ${PYTHON_EXECUTABLE} -m pip "install" ${PIPMODE} ${module} RESULT_VARIABLE SUCCESS)
        if (NOT "${SUCCESS}" STREQUAL "0")
            execute_process(COMMAND pip "install" ${PIPMODE} ${module} RESULT_VARIABLE SUCCESS)
            if (NOT "${SUCCESS}" STREQUAL "0")
                message(WARNING "Failed to automatically install ${module}. Please install manually")
                SET(${RESULT_NAME}  ${SUCCESS} PARENT_SCOPE)
            endif()
        endif()
ENDFUNCTION()
