name: Build

on: [push, pull_request]

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 2
  CTEST_PARALLEL_LEVEL: 2
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Install required dependencies using apt-get
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install gfortran libopenblas-dev libfftw3-dev libhdf5-dev libnfft3-dev

    - name: Install required dependencies using brew
      if: matrix.os == 'macos-latest'
      run: |
        brew install gcc fftw hdf5 wentzell/triqs/nfft
        echo "PATH=$(brew --prefix)/opt/gcc/bin:$PATH" >> $GITHUB_ENV

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Configure
      run: |
        cmake -B build \
              -DCMAKE_Fortran_COMPILER=gfortran \
              -DCMAKE_C_COMPILER=gcc \
              -DCMAKE_CXX_COMPILER=g++

    - name: Build
      run: cmake --build build --verbose

    - name: Test
      run: |
        env "PYTHONPATH=$PWD/w2dyn/auxiliaries:$PYTHONPATH" python3 -c 'import CTQMC'
        env "PYTHONPATH=$PWD/w2dyn/maxent:$PYTHONPATH" python3 -c 'import MAXENT'
        cd build
        ctest --output-on-failure
